# Calamares users module — Axon OS

---

defaultGroups:
  - adm
  - cdrom
  - dip
  - lpadmin
  - plugdev
  - sudo

autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: false

passwordRequirements:
  minLength: 4

user:
  shell: /bin/bash
